name: CI y Alerta

on:
  push:
    branches:
      - main

jobs:
  test-y-notificacion:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Ejecutar pruebas unitarias
        run: |
          python -m unittest test_hola.py

      - name: Enviar notificación a ntfy
        if: success()
        run: |
          curl -H "Title: Push Exitoso" \
               -d "Pruebas unitarias completadas correctamente en ${{ github.repository }}" \
               https://ntfy.sh/devops-itla